### ISSUE TITLE
CertBundKontakt-Expert and CertBundRule-Expert bot installation

### ISSUE THREAD

**Issue by kodebrain** [Intevation/intelmq-certbund-contact#21]
Hi,

How can the certbund bots be installed into Intelmq?
All the prerequisite for setting up the contactdb is completed
I followed up on the tool below to install the bot, but the bots aren't starting from the intelmq-manager
https://github.com/jhemp/intelmq-tools
The installation path for the bots is /usr/lib/python3/dist-packages/intelmq/bots/experts

**Comment by sebix** [comment]
jhemp's intelmq-tools are not mentioned in the docs of mailgen and certbund-contact. We did not test if they are compatible.

Did you install intelmq from PyPI or the repository, or with deb/rpm-packages?

**Comment by kodebrain** [comment]
Installed intelmq, API, and Manager using the deb native packages, version 3.0.1

**Comment by sebix** [comment]
The current version of intelmq is actuall 3.1.0. Did you try an `apt update` and `apt upgrade`?

Does `apt install intelmq-certbund-contact` work for you?

**Comment by kodebrain** [comment]
Ran update and upgrade with no issues
During the installation of certbund-contact, receive the error "Unable to locate package intelmq-certbund-contact

**Comment by sebix** [comment]
Okay, that should not happen. With operating system version do you use?

**Comment by sebix** [comment]
oh, sorry, I had these packages only in the unstable repo. I'll add them to the stable repo as well and then give you a head's up once the packages are ready

**Comment by arpreacher** [comment]
Great. Once the packages are available, Can I expect the two bots to be available under the expert section in Intelmq-manager or are there any manual configuration changes that need to be done

**Comment by sebix** [comment]
No extra installation steps are required.

**Comment by sebix** [comment]
btw: if you use ubuntu 20.04 you could also use http://apt.intevation.de/dists/focal/intelmq-testing/ (although the URL contains "testing", the software is stable)

**Comment by sebix** [comment]
You should now find `intelmq-mailgen` and `intelmq-certbund-contact` in the repos. It may take some time for the mirrors to sync, though.

**Comment by arpreacher** [comment]
thank you. the bots are now visible. After the upgrade, I noticed Postgresql bot missing from the output section. Is this expected?

**Comment by sebix** [comment]
The postgres output bot was renamed to sql (supporting not only postgres, but also sqlite and mssql): https://intelmq.readthedocs.io/en/latest/user/bots.html#sql

**Comment by kodebrain** [comment]
`tail -f CERTBundKontakt-Expert.log 
2023-02-01 16:21:35,320 - CERTBundKontakt-Expert - INFO - CERTBundKontaktExpertBot initialized with id CERTBundKontakt-Expert and intelmq 3.0.2 and python 3.8.10 (default, Nov 14 2022, 12:59:47) as process 9605.
2023-02-01 16:21:35,320 - CERTBundKontakt-Expert - INFO - Bot is starting.
2023-02-01 16:21:35,377 - CERTBundKontakt-Expert - INFO - Bot initialization completed.
2023-02-13 15:52:29,704 - CERTBundKontakt-Expert - INFO - Received SIGTERM.
2023-02-13 15:52:29,708 - CERTBundKontakt-Expert - INFO - Bot stopped.
2023-02-13 16:15:28,440 - CERTBundKontakt-Expert - INFO - CERTBundKontaktExpertBot initialized with id CERTBundKontakt-Expert and intelmq 3.1.0 and python 3.8.10 (default, Nov 14 2022, 12:59:47) as process 1795.
2023-02-13 16:15:28,440 - CERTBundKontakt-Expert - INFO - Bot is starting.
2023-02-13 16:15:28,489 - CERTBundKontakt-Expert - INFO - Bot initialization completed.
2023-02-13 16:19:10,631 - CERTBundKontakt-Expert - INFO - Received SIGTERM.
2023-02-13 16:19:10,642 - CERTBundKontakt-Expert - INFO - Bot stopped.`

`sudo intelmqctl status
Bot Abusix-Expert is running.
Bot CERTBundKontakt-Expert is stopped.
Bot CERTBundRule-Expert is stopped.
Bot CymruCAPProgram-Parser is running.
Bot HTTP-Collector-TeamCymru is running.
Bot SQL-Output is stopped.
Bot cymru-whois-expert is running.
Bot deduplicator-expert is running.
Bot feodo-tracker-collector is running.
Bot feodo-tracker-parser is running.
Bot file-output is running.
Bot gethostbyname-1-expert is running.
Bot gethostbyname-2-expert is running.
Bot spamhaus-drop-collector is running.
Bot spamhaus-drop-parser is running.
Bot taxonomy-expert is running.
Traceback (most recent call last):
  File "/usr/bin/intelmqctl", line 11, in <module>
    load_entry_point('intelmq==3.1.0', 'console_scripts', 'intelmqctl')()
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 1293, in main
    return x.run()
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 428, in run
    retval, results = args.func(**args_dict)
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 489, in bot_status
    return self.botnet_status(group=group)
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 604, in botnet_status
    botnet_status[bot_id] = self.bot_status(bot_id)[1]
  File "/usr/lib/python3/dist-packages/intelmq/bin/intelmqctl.py", line 491, in bot_status
    status = self._processmanager.bot_status(bot_id)
  File "/usr/lib/python3/dist-packages/intelmq/lib/processmanager.py", line 273, in bot_status
    module = self._runtime_configuration[bot_id]['module']
KeyError: 'module'
`

**Comment by sebix** [comment]
Looks like your configuration is broken and the `module` entry of a bot is missing. That appears to be unrelated to the CERTBundKontakt-Expert and CERTBundRule-Expert as the output shows.

Open `/etc/intelmq/runtime.yaml` and go to the block _after_ the `taxonomy-expert` and fix it.

**Comment by kodebrain** [comment]
I removed positions.conf and somehow there was an undefined bot which i deleted and restarted using ``intelmqctl restart`` 
the positions.conf get generated and the error is no longer there.
